[package]
name = "evtide"
version = "0.0.1"
edition = "2024"
description = "Experimental cross-platform event-camera I/O and visualization toolkit."
repository = "https://github.com/coekfung/evtide"
homepage = "https://github.com/coekfung/evtide"
documentation = "https://docs.rs/evtide"
readme = "README.md"
license = "MIT"
keywords = ["event-camera", "neuromorphic", "vision"]
categories = ["computer-vision", "multimedia"]

[dependencies]
